-- 001_init.sql
-- Stockroom core schema: settings, products, units.  (MySQL 8.0.16+, InnoDB)
-- Everything here is idempotent-friendly (IF NOT EXISTS) so re-running is safe.
--
-- Collation: utf8mb4_0900_ai_ci is case-INsensitive, so plain `=`, `LIKE` and
-- UNIQUE indexes on text columns already compare case-insensitively. That is
-- what makes SKUs and serials unique / searchable regardless of case without
-- any lower(...) expression indexes.
--
-- UUIDs are stored as CHAR(36) and generated by the application
-- (crypto.randomUUID()), so the app knows each new row's id without RETURNING.

-- ---------------------------------------------------------------------------
-- settings: a single-row configuration table (id is pinned to 1)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
    id                       SMALLINT      NOT NULL DEFAULT 1,
    company_name             VARCHAR(200)  NOT NULL DEFAULT 'My Company',
    serial_prefix            VARCHAR(16)   NOT NULL DEFAULT '',
    default_warranty_months  INT           NOT NULL DEFAULT 12,
    low_stock_threshold      INT           NOT NULL DEFAULT 5,
    updated_at               DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    CONSTRAINT settings_singleton CHECK (id = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------------
-- products: a product line. `next_seq` is the per-product serial counter and
-- is mutated ONLY inside a transaction that holds a row lock on the product
-- (SELECT ... FOR UPDATE), which is what makes serial allocation race-free.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id               CHAR(36)       NOT NULL,
    name             VARCHAR(200)   NOT NULL,
    sku              VARCHAR(64)    NOT NULL,
    description      VARCHAR(2000)  NOT NULL DEFAULT '',
    warranty_months  INT            NOT NULL DEFAULT 12,
    serial_prefix    VARCHAR(16)    NULL,      -- optional per-product override of settings.serial_prefix
    next_seq         INT            NOT NULL DEFAULT 1,
    created_at       DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at       DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    -- SKU is unique, case-insensitively (via the _ci collation).
    UNIQUE KEY products_sku_key (sku),
    KEY products_created_at_idx (created_at),
    CONSTRAINT products_warranty_months_chk CHECK (warranty_months >= 0),
    CONSTRAINT products_next_seq_chk        CHECK (next_seq >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------------
-- units: an individual physical unit. This is the heart of the system: it ties
-- the manufacturer's serial (for warranty claims with the vendor) to the
-- internally generated serial (your own tracking id), 1:1.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS units (
    id                   CHAR(36)       NOT NULL,
    product_id           CHAR(36)       NOT NULL,
    seq                  INT            NOT NULL,            -- per-product sequence number
    internal_serial      VARCHAR(128)   NOT NULL,            -- generated, globally unique
    manufacturer_serial  VARCHAR(128)   NULL,                -- supplier serial (nullable: may be unknown at intake)
    status               ENUM('in_stock', 'sold', 'returned', 'defective') NOT NULL DEFAULT 'in_stock',
    intake_date          DATE           NOT NULL DEFAULT (CURRENT_DATE),
    warranty_start       DATE           NULL,                -- defaults to intake_date on intake
    warranty_months      INT            NOT NULL DEFAULT 12,
    sold_to              VARCHAR(200)   NULL,
    sold_date            DATE           NULL,
    notes                VARCHAR(2000)  NOT NULL DEFAULT '',
    created_at           DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at           DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),

    -- The internal serial is globally unique — it is your primary tracking id.
    UNIQUE KEY units_internal_serial_key (internal_serial),

    -- The per-product sequence number is unique within a product. Combined with
    -- the FOR UPDATE lock on the product row during intake, this is a hard
    -- guarantee against duplicate serials even under concurrent intake.
    UNIQUE KEY units_seq_per_product_key (product_id, seq),

    -- Manufacturer serials are NOT unique.
    -- Multiple physical units may have the same manufacturer serial.
    KEY units_mfr_serial_idx (manufacturer_serial),

    -- Lookup / filter support. (product_id is covered by the keys above.)
    KEY units_status_idx (status),
    KEY units_created_at_idx (created_at),

    CONSTRAINT units_product_fk FOREIGN KEY (product_id)
        REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT units_warranty_months_chk CHECK (warranty_months >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
